# site settings
title: Aron Nisbel
subtitle:
email: aron.nisbel@hotmail.com
description: This is my UX Design Portfolio
baseurl: # the subpath of your site, e.g. /blog
url: https://aronnisbel.github.io
author:
street_address: Hökmossevägen 36A
city: Hägersten
state: Stockholms län
zip_code: 11543
country: Sweden
phone: +46 73 821 32 22

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url:
github_url: https://github.com/aronnisbel
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/aronnisbel/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
